project:
  name: quickstart-microsoft-sql
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  ec2-li-2016:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'yes'
      SQLServerVersion: '2016'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - eu-west-2
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ds:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - eu-west-1
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ds-3rdaz-full:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_3]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: full
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ds-3rdaz-witness:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_3]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: witness
      WSFCFileServerPrivateIP: 10.0.64.200
    regions:
    - us-west-2
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ec2:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - eu-central-1
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ec2-3rdaz-full:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_3]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 10.0.0.0/16
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: full
    regions:
    - eu-west-3
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ec2-3rdaz-witness:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_3]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      ThirdAZ: witness
      WSFCFileServerPrivateIP: 10.0.64.200
    regions:
    - ap-southeast-1
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ec2-ebs-io1:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'no'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
      VolumeIops: '1000'
      VolumeSize: '200'
      VolumeType: io1
    regions:
    - ca-central-1
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ec2-li-2017:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLLicenseProvided: 'yes'
      SQLServerVersion: '2017'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - us-west-1
    s3_bucket: ''
    template: templates/sql-master.template
  mssql-ec2-sql-2016:
    parameters:
      ADScenarioType: Microsoft AD on Amazon EC2
      ADServer1NetBIOSName: SQLDC1
      ADServer2NetBIOSName: SQLDC2
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      RDGWCIDR: 0.0.0.0/0
      SQLServerVersion: '2016'
      SQLServiceAccountPassword: $[taskcat_genpass_16]
    regions:
    - us-east-2
    s3_bucket: ''
    template: templates/sql-master.template
